/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tokio.otp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TwoFactorConfigs service. Represents a row in the &quot;OTP_TwoFactorConfigs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokio.otp.model.impl.TwoFactorConfigsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokio.otp.model.impl.TwoFactorConfigsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TwoFactorConfigs
 * @generated
 */
@ProviderType
public interface TwoFactorConfigsModel
	extends BaseModel<TwoFactorConfigs>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a two factor configs model instance should use the {@link TwoFactorConfigs} interface instead.
	 */

	/**
	 * Returns the primary key of this two factor configs.
	 *
	 * @return the primary key of this two factor configs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this two factor configs.
	 *
	 * @param primaryKey the primary key of this two factor configs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the two factor configs ID of this two factor configs.
	 *
	 * @return the two factor configs ID of this two factor configs
	 */
	public long getTwoFactorConfigsId();

	/**
	 * Sets the two factor configs ID of this two factor configs.
	 *
	 * @param twoFactorConfigsId the two factor configs ID of this two factor configs
	 */
	public void setTwoFactorConfigsId(long twoFactorConfigsId);

	/**
	 * Returns the config name of this two factor configs.
	 *
	 * @return the config name of this two factor configs
	 */
	@AutoEscape
	public String getConfigName();

	/**
	 * Sets the config name of this two factor configs.
	 *
	 * @param configName the config name of this two factor configs
	 */
	public void setConfigName(String configName);

	/**
	 * Returns the config value of this two factor configs.
	 *
	 * @return the config value of this two factor configs
	 */
	@AutoEscape
	public String getConfigValue();

	/**
	 * Sets the config value of this two factor configs.
	 *
	 * @param configValue the config value of this two factor configs
	 */
	public void setConfigValue(String configValue);

	/**
	 * Returns the config status of this two factor configs.
	 *
	 * @return the config status of this two factor configs
	 */
	public boolean getConfigStatus();

	/**
	 * Returns <code>true</code> if this two factor configs is config status.
	 *
	 * @return <code>true</code> if this two factor configs is config status; <code>false</code> otherwise
	 */
	public boolean isConfigStatus();

	/**
	 * Sets whether this two factor configs is config status.
	 *
	 * @param configStatus the config status of this two factor configs
	 */
	public void setConfigStatus(boolean configStatus);

	/**
	 * Returns the group ID of this two factor configs.
	 *
	 * @return the group ID of this two factor configs
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this two factor configs.
	 *
	 * @param groupId the group ID of this two factor configs
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this two factor configs.
	 *
	 * @return the company ID of this two factor configs
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this two factor configs.
	 *
	 * @param companyId the company ID of this two factor configs
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the modified date of this two factor configs.
	 *
	 * @return the modified date of this two factor configs
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this two factor configs.
	 *
	 * @param modifiedDate the modified date of this two factor configs
	 */
	public void setModifiedDate(Date modifiedDate);

}