/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tokio.otp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TwoFactor service. Represents a row in the &quot;OTP_TwoFactor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tokio.otp.model.impl.TwoFactorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tokio.otp.model.impl.TwoFactorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TwoFactor
 * @generated
 */
@ProviderType
public interface TwoFactorModel extends BaseModel<TwoFactor>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a two factor model instance should use the {@link TwoFactor} interface instead.
	 */

	/**
	 * Returns the primary key of this two factor.
	 *
	 * @return the primary key of this two factor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this two factor.
	 *
	 * @param primaryKey the primary key of this two factor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the two factor ID of this two factor.
	 *
	 * @return the two factor ID of this two factor
	 */
	public long getTwoFactorId();

	/**
	 * Sets the two factor ID of this two factor.
	 *
	 * @param twoFactorId the two factor ID of this two factor
	 */
	public void setTwoFactorId(long twoFactorId);

	/**
	 * Returns the group ID of this two factor.
	 *
	 * @return the group ID of this two factor
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this two factor.
	 *
	 * @param groupId the group ID of this two factor
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this two factor.
	 *
	 * @return the company ID of this two factor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this two factor.
	 *
	 * @param companyId the company ID of this two factor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this two factor.
	 *
	 * @return the user ID of this two factor
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this two factor.
	 *
	 * @param userId the user ID of this two factor
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this two factor.
	 *
	 * @return the user uuid of this two factor
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this two factor.
	 *
	 * @param userUuid the user uuid of this two factor
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this two factor.
	 *
	 * @return the create date of this two factor
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this two factor.
	 *
	 * @param createDate the create date of this two factor
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this two factor.
	 *
	 * @return the modified date of this two factor
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this two factor.
	 *
	 * @param modifiedDate the modified date of this two factor
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the verification type of this two factor.
	 *
	 * @return the verification type of this two factor
	 */
	@AutoEscape
	public String getVerificationType();

	/**
	 * Sets the verification type of this two factor.
	 *
	 * @param verificationType the verification type of this two factor
	 */
	public void setVerificationType(String verificationType);

	/**
	 * Returns the verification data of this two factor.
	 *
	 * @return the verification data of this two factor
	 */
	@AutoEscape
	public String getVerificationData();

	/**
	 * Sets the verification data of this two factor.
	 *
	 * @param verificationData the verification data of this two factor
	 */
	public void setVerificationData(String verificationData);

	/**
	 * Returns the expiration date of this two factor.
	 *
	 * @return the expiration date of this two factor
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this two factor.
	 *
	 * @param expirationDate the expiration date of this two factor
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the used of this two factor.
	 *
	 * @return the used of this two factor
	 */
	public boolean getUsed();

	/**
	 * Returns <code>true</code> if this two factor is used.
	 *
	 * @return <code>true</code> if this two factor is used; <code>false</code> otherwise
	 */
	public boolean isUsed();

	/**
	 * Sets whether this two factor is used.
	 *
	 * @param used the used of this two factor
	 */
	public void setUsed(boolean used);

	/**
	 * Returns the disabled of this two factor.
	 *
	 * @return the disabled of this two factor
	 */
	public boolean getDisabled();

	/**
	 * Returns <code>true</code> if this two factor is disabled.
	 *
	 * @return <code>true</code> if this two factor is disabled; <code>false</code> otherwise
	 */
	public boolean isDisabled();

	/**
	 * Sets whether this two factor is disabled.
	 *
	 * @param disabled the disabled of this two factor
	 */
	public void setDisabled(boolean disabled);

}